spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans Service related Prod APIs"
  contactDetails:
    name: "Srikanth - Product Owner"
    email: "srikanth@gmail.com"
  onCallSupport:
    91-9876787656
    91-9787654567